RDK-45434 : Add L2 test specification and implementation
rdkcentral/rdk-halif-test-rmf_audio_capture pull request #5
Opened 2024-04-03 20:09 UTC by chaithents

2024-04-08 09:03 UTC, Ulrond commented
can you share the output of the tests, so we can review it..

-> It must run completely without crashing on x86
-> It must run and can you give a report of the testing suite on arm target.

2024-04-08 09:05 UTC, Ulrond commented
this is a fork of the repo and not a branch off the actual repo, please re-do it to be a branch see -> https://github.com/rdkcentral/rdk-halif-test-rmf_audio_capture/blob/main/CONTRIBUTING.md

2024-04-08 09:07 UTC, Ulrond requested changes
blocked on this being a fork.

please delete this fork and create a branch

2024-04-08 09:08 UTC, Ulrond commented on docs/pages/L2_TestSpecification.md
> +  - `ut-core` \- Common Testing Framework <https://github.com/comcast-sky/rdk-components-ut-core>, which wraps a open-source framework that can be expanded to the requirements for future comcast-sky
these are all wrong, rdkcentral/ut-core was correct

2024-04-08 09:11 UTC, Ulrond commented
Your testing requirements conflict with here -> https://github.com/rdkcentral/rdk-halif-test-rmf_audio_capture/pull/4/files#diff-cfbf2cf5c46f28c9994f07c4d9430995ba31f357d54ce87b92180ddd4780adbf

2024-04-11 12:09 UTC, Ulrond commented
> Your testing requirements conflict with here -> https://github.com/rdkcentral/rdk-halif-test-rmf_audio_capture/pull/4/files#diff-cfbf2cf5c46f28c9994f07c4d9430995ba31f357d54ce87b92180ddd4780adbf

> Let me discuss internally and see what the best approach maybe, could be merge you changes first, then rebase on the document updates.

2024-09-23 01:06 UTC, srinivasgtl commented
All L2 updates available in #4

2024-09-23 01:06 UTC, closed without merging