Feature/gh7 enhancederrorcode disable
rdkcentral/rdk-halif-test-rmf_audio_capture pull request #8
Opened 2024-05-09 11:47 UTC by thanushreevani

2024-05-09 11:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/rdk-halif-test-rmf_audio_capture?pullRequest=8) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/rdk-halif-test-rmf_audio_capture?pullRequest=8) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: hari22yuva<br/>:x: thanushreevani<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/rdk-halif-test-rmf_audio_capture?pullRequest=8) it.</sub>

2024-05-10 10:10 UTC, hari22yuva commented
hi @thanushreevani ,
write a description what this PR is

2024-05-10 11:16 UTC, hari22yuva requested changes
if RMF_INVALID_STATE,RMF_INVALID_HANDLE are enhanced error code what is normal codes, that we need to guess and add else case not disabling the calling function

2024-05-13 12:15 UTC, thanushreevani commented on src/test_l1_rmfAudioCapture.c
> +	#endif
Done

2024-05-27 08:08 UTC, thanushreevani commented on src/test_l1_rmfAudioCapture.c
> +	/*if(RMF_INVALID_STATE != result){
Done

2024-05-30 10:35 UTC, srinivasgtl approved these changes
approved

2024-06-03 09:39 UTC, hari22yuva approved these changes
changes looks ok

2024-06-05 10:50 UTC, merged